# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.

  
  nfs_ip  = "192.168.51.100"
  db_ip  = "192.168.51.110"
  ucp_ip  = "192.168.51.10"
  nat_net = "10.3/16"
  
  # config.ssh.shell = "/bin/bash -c 'BASH_ENV=/etc/profile exec bash'"


  config.vm.define "nfs" do |nfs|
  	nfs.vm.box = "docker-nfs"
  	nfs.vm.box_url = "../../builds/centos-7.3-nfs.virtualbox.box"
  	nfs.vm.synced_folder ".", "/vagrant", type: "virtualbox"  , disabled: true
  	nfs.vm.network "private_network", ip: nfs_ip
  	nfs.vm.hostname = "nfs.docker.vm"
	nfs.vm.provider "virtualbox" do |vb|
  		vb.memory = "1024"
		vb.cpus = "1"
    		vb.customize ["modifyvm", :id, "--natnet1", nat_net]   
  	end
  end

#  config.vm.define "db" do |db|
#  	db.vm.box = "evryfs/oracle12c-ee"
#  	# db.vm.box_url = "evryfs/oracle12c-ee"
#  	db.vm.synced_folder ".", "/vagrant", type: "virtualbox"  , disabled: true
#  	db.vm.network "private_network", ip: db_ip
#  	db.vm.hostname = "nfs.docker.vm"
#	db.vm.provider "virtualbox" do |vb|
#  		vb.memory = "4096"
#		vb.cpus = "2"
#    		vb.customize ["modifyvm", :id, "--natnet1", nat_net]   
#  	end
#  end

  config.vm.define "ucp" do |ucp|
  	ucp.vm.box = "docker-ucp"
  	ucp.vm.box_url = "../../builds/centos-7.3-ucp.virtualbox.box"
  	ucp.vm.synced_folder ".", "/vagrant", type: "virtualbox" , disabled: true
  	ucp.vm.network "private_network", ip: ucp_ip
  	ucp.vm.hostname = "nfs.docker.vm"
	ucp.vm.provider "virtualbox" do |vb|
  		vb.memory = "4096"
		vb.cpus = "2"
    		vb.customize ["modifyvm", :id, "--natnet1", nat_net]   
  	end
 	# ucp.vm.provision "shell" , privileged: true , path: "./install_ucp.sh"
 	ucp.vm.provision "shell" , privileged: true , path: "./mount_nfs.sh" , args: nfs_ip
  end

  # config.vm.box = "docker-ucp"
  # config.vm.box_url = "../../builds/centos-7.3-ucp.virtualbox.box"
  # config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  # config.vm.network "private_network", ip: "192.168.51.10"
  # config.vm.hostname = "ucp01.docker.vm"


  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  #   
  #   vb.customize ["modifyvm", :id, "--natnet1", nat_net]   
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
